#if defined _vm_resources_included
  #endinput
#endif
#define _vm_resources_included

#define MODEL_VAMPIRE_HOST "models/vampire/v01/vampire_host.mdl"
#define MODEL_VAMPIRE_HANDS_HOST "models/vampire/v01/vampire_hands_host.mdl"
#define MODEL_VAMPIRE_NORMAL "models/vampire/v01/vampire_normal.mdl"
#define MODEL_VAMPIRE_HANDS_NORMAL "models/vampire/v01/vampire_hands_normal.mdl"

#define MODEL_HUNTER_KNIFE "models/vampire/v01/hunter_knife.mdl"

#define MODEL_LYCAN "models/vampire/v01/lycan.mdl"
#define MODEL_LYCAN_HANDS "models/vampire/v01/lycan_hands.mdl"

#define SOUND_PREPARE ""

#define SOUND_BOOST_ACTIVATE ""

#define SOUND_VAMPIRE_SPAWN ""
#define SOUND_VAMPIRE_DIE ""
#define SOUND_VAMPIRE_PAIN ""
#define SOUND_VAMPIRE_EXECUTED ""
#define SOUND_VAMPIRE_REGENERATE ""

#define SOUND_LYCAN_SPAWN ""
#define SOUND_LYCAN_DIE ""

#define SOUND_HUNTER_DIE ""